# Generated by Django 4.2.3 on 2023-07-07 14:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('Company', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Image', models.ImageField(upload_to='')),
                ('Discription', models.TextField()),
                ('Founder', models.CharField(max_length=100)),
                ('Established_On', models.DateField()),
                ('Company_Type', models.CharField(max_length=100)),
                ('Profit', models.IntegerField()),
                ('Projects', models.TextField()),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
